### ISSUE TITLE
Dataset organization

### ISSUE THREAD

**Issue by jameelhassan** [valeoai/UNIT#1]
Hi, 
Thanks for releasing the code for this interesting work. 

Could you specify how the dataset should be organized, or could you point to a page where I can follow that. Thanks.

**Comment by CSautier** [comment]
Hi, I just pushed a version that simplified a bit the data organisation for SemanticKITTI, and explained it in the README. Is that clearer now?

**Comment by jameelhassan** [comment]
Thank you, that is clearer. 

Can you also clarify about using preprocessed input segments. I would like to run the codebase to understand it better. So if I am to use the SemanticKitti preprocessed segments from Patchwork++ that is linked, I assume I do not need the original dataset?

If that is correct, can I know whats the path I should have the preprocessed dataset in. The preprocessed data seems to be a set of folders with the sequence names 00 to 10.

**Comment by CSautier** [comment]
It should look like this:
```
UNIT
├── datasets
│   ├── semantickitti
│   │   │── sequences
│   │   │── assets/segments_gridsample/08
```
You will still need the original dataset, as those segments do not contain the points coordinates, but you might not need the labels if you do not plan on evaluating the results.
The segments for SemanticKITTI are only provided because the original Patchwork code is written for ROS, and is quite difficult to work with.

**Comment by jameelhassan** [comment]
Thank you very much. 

Since this is my first time working with Semantic Kitti, can you confirm if I need to download everything in this link or only specific ones https://www.semantic-kitti.org/dataset.html#download

**Comment by CSautier** [comment]
You need the biggest one of 80GB, but you might as well download the rest as it will be necessary if you decide to modify the preprocessing or evaluate the results

**Comment by jameelhassan** [comment]
Understood, thank you.
