### ISSUE TITLE
About Inference

### ISSUE THREAD

**Issue by ljwwwiop** [valeoai/UNIT#2]
Great work, and thank you for open-sourcing it. 
However, I encountered an issue when running your code – the inference command doesn't seem to work and appears to have a bug. 
The training phase runs fine, though.

I encountered the following error when running inference using the command you provided: 
![image](https://github.com/user-attachments/assets/17fb6d40-55da-4330-b713-f1e10bc09676)
![image](https://github.com/user-attachments/assets/a7ebd365-e9df-431a-bed1-67c814b2d371)
![image](https://github.com/user-attachments/assets/9c6ffb4a-9725-4e59-a35e-e1d284a3bd08)

I found that there was an issue with the initialization of the NoGpu class in the voxelize_fixed function. The issue was resolved after I made modifications and ran the code.

![image](https://github.com/user-attachments/assets/45303c9e-0f17-44f0-9746-d5561f2041da)
![image](https://github.com/user-attachments/assets/123a64bd-c417-42fa-b94a-8ea1932ef317)

**python inference_instance_segmentation.py general.experiment_name=sk_temporal general.checkpoint=saved/sk_temporal/last-epoch.ckpt data.batch_size=1 general.forward_queries=true data/datasets=semantic_kitti data.predict_mode=validation**

I followed the inference command you provided, but it seems I am unable to get the prediction results. After fixing the bug, I found that this might be an ongoing issue. Could you please help check the inference command? I look forward to your response. Thank you!

**Comment by CSautier** [comment]
Hi, thank you for your interest in the project.
There is indeed a problem, line 460 in trainer.py has been duplicated. It should not be there, and was not there in the development code I had. Removing it should fix the issue. Thanks as well for noticing I forgot some keywords in the NoGpu class. I will push a fixed version soon.

**Comment by CSautier** [comment]
I pushed the modifications. Let me know if you still run into some issues.

**Comment by ljwwwiop** [comment]
Thank you so much for your reply! My inference code is working now! 
I really admire your work and fully agree with the core motivation of the paper—online segmentation and self-supervised learning. This approach indeed seems like a promising direction for large-scale training in autonomous driving scenarios. At the same time, I have a couple of ideas I’d love to discuss with you.

First, in real-world autonomous driving scenarios, the vehicle’s driving sequences are typically quite long. In such cases, would it make sense to incorporate more dense attention mechanisms (like attention residuals) to guide cross-frame information propagation, ensuring that future frames maintain a strong focus on moving vehicles?

Second, regarding the way features are updated during online learning: your paper assumes the pseudo-labels are reliable and uses contrastive learning and instance loss to update the network. However, pseudo-labels might contain some noise, which could accumulate over time. Do you think it might be possible to adjust the updating strategy to better mitigate this issue?

These are just some of my thoughts—they might not be entirely accurate, haha! Thanks again for your reply, and I look forward to discussing more with you!

**Comment by ljwwwiop** [comment]
If it's convenient for you, may I reach out to you via email in the future?

**Comment by CSautier** [comment]
Sure, I'd be happy to discuss by email. I let you contact me, and will close this issue now.
